College_rating/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import  settings


admin.site.site_header = "VIKRAM SHIMHAPURI UNIVERSITY IN NELLURE "
admin.site.site_title = "VSU-RATING COLLGE"
admin.site.index_title = "Welcome to VSU College"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls'))
# + static(settings.STATIC_URL,document_root=settings.STATIC_ROOT),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout")
]

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = "main"

urlpatterns = [
    path('',views.main,name='main'),
    path('home/', views.home,name="home"),
    path('about/',views.about,name="abt"),

    path('details/<int:id>/', views.detail, name="detail"),
    path('addcollege/', views.add_movies, name="add_movies"),
    path('editcollege/<int:id>/', views.edit_movies, name="edit_movies"),
    path('deletecollege/<int:id>/', views.delete_movies, name="delete_movie"),
    path('addreview/<int:id>/', views.add_review, name="add_review"),
    path('editreview/<int:movie_id>/<int:review_id>/', views.edit_review, name="edit_review"),
    path('deletereview/<int:movie_id>/<int:review_id>/', views.delete_review, name="delete_review"),


    path('contact/',views.contact,name="contact"),
    path('gallery/',views.gallery,name="gallery"),
    
    path('email/',views.Email_view,name="email"),
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import related
# Create your models here.
class Movie(models.Model):
#   for college table convert 
    name = models.CharField(max_length=300)
    director = models.CharField(max_length=300)
    cast = models.CharField(max_length=800)
    description = models.TextField( max_length=5000)
    release_date = models.DateField()
    averageRating = models.FloatField(default=0)

    image = models.URLField(default=None, null=True)
    
    # image = models.ImageField(upload_to='images/')


    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "COLLEGE"

class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=5000)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name_plural = "COLLEGE_REVIEW"


class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    # mobile = models.IntegerField()
    comment = models.TextField(max_length=100)
    
    def __str__(self):
        return self.first_name
    
    class Meta:
        verbose_name_plural = 'ENQUIRY DATA'



# gallery

class Image(models.Model):
   
    img = models.ImageField(upload_to='images/')
    name = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural = "IMAGES"


# email process 

class EmailData(models.Model):
    email = models.EmailField(max_length=500)
    subject = models.CharField(max_length=300)
    message = models.TextField(max_length=1000)

    def __str__(self) -> str:
        return self.email

main/forms.py
from django import forms
from .models import *

# movie add form
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'director', 'cast', 'description', 'release_date', 'image')

        


        labels = {"name":"Enter Your College Name",
        'director':"Enter Your College-Direct Name",
        'cast':'Your College Fees',
        'description':'Enter Your College Description/Openion',
        'release_date':'Enter Your Joining Date',
        'image':"Uplode Your College Photo",
        
        }
        
          
        
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("comment", "rating")
        


# contact forma page

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'



# image gallery form

class ImagesForms(forms.ModelForm):
    class Meta:
        model = Image
        fields=['img']
        labels = {'img':''}

main/views.py
import django
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from django.db.models import Avg




from django.core.mail import send_mail 
# mail import project 
from College_rating.settings import EMAIL_HOST_USER


# messages disply from settings to views import

from django.contrib import messages
# Create your views here.

def main(request):
    return render(request, 'main/mainhome.html')

def about(request):
    return render(request, 'main/about.html')



def home(request):
    query = request.GET.get("title")
    allMovies = None
    if query:
        allMovies = Movie.objects.filter(name__icontains=query)
    else:
        allMovies = Movie.objects.all()  # select * from movie
    
    context = {
        "movies": allMovies,
    }

    return render(request, 'main/index.html', context)

# detail page
def detail(request, id):
    movie = Movie.objects.get(id=id) # select * from movie where id=id
    reviews = Review.objects.filter(movie=id).order_by("-comment")

    average = reviews.aggregate(Avg("rating"))["rating__avg"]
    if average == None:
        average = 0
    average = round(average, 2)
    context = {
        "movie": movie,
        "reviews": reviews,
        "average": average
    }
    return render(request, 'main/details.html', context)


# add movies to the database
def add_movies(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method == "POST":
                form = MovieForm(request.POST or None)

                # check if the form is valid
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    messages.success(request,"Your data has saved succesfullly")
                    return redirect("main:home")
            else:
                form = MovieForm()
            return render(request, 'main/addmovies.html', {"form": form, "controller": "ADD COLLEGE"})
        
        # if they are not admin
        else:
            return redirect("main:home")

    # if they are not loggedin
    return redirect("accounts:login")    


# edit the movie
def edit_movies(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # get the movies linked with id
            movie = Movie.objects.get(id=id)

            # form check
            if request.method == "POST":
                form = MovieForm(request.POST or None, instance=movie)
                # check if form is valid
                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("main:detail", id)
            else:
                form = MovieForm(instance=movie)
            return render(request, 'main/addmovies.html', {"form": form, "controller": "Edit Movies"})
        # if they are not admin
        else:
            return redirect("main:home")

    # if they are not loggedin
    return redirect("accounts:login") 


# delete movies
def delete_movies(request, id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            # get the moveis
            movie = Movie.objects.get(id=id)

            # delte the movie
            movie.delete()
            return redirect("main:home")
        # if they are not admin
        else:
            return redirect("main:home")

    # if they are not loggedin
    return redirect("accounts:login") 

def add_review(request, id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=id)
        if request.method == "POST":
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST["comment"]
                data.rating = request.POST["rating"]
                data.user = request.user
                data.movie = movie
                data.save()
                return redirect("main:detail", id)
        else:
            form = ReviewForm()
        return render(request, 'main/details.html', {"form": form})
    else:
        return redirect("accounts:login")


# edit the review
def edit_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        # review
        review = Review.objects.get(movie=movie, id=review_id)

        # check if the review was done by the logged in user
        if request.user == review.user:
            # grant permission
            if request.method == "POST":
                form = ReviewForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating > 10) or (data.rating < 0):
                         error = "Out or range. Please select rating from 0 to 10."
                         return render(request, 'main/editreview.html', {"error": error, "form": form})
                    else:
                        data.save()
                        return redirect("main:detail", movie_id)
            else:
                form = ReviewForm(instance=review)
            return render(request, 'main/editreview.html', {"form": form})
        else:
            return redirect("main:detail", movie_id)
    else:
        return redirect("accounts:login")


# delete reivew
def delete_review(request, movie_id, review_id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=movie_id)
        # review
        review = Review.objects.get(movie=movie, id=review_id)

        # check if the review was done by the logged in user
        if request.user == review.user:
            # grant permission to delete
            review.delete()

        return redirect("main:detail", movie_id)
            
    else:
        return redirect("accounts:login")

def contact(request):
    if request.method == "POST":
     da = ContactForm(request.POST)
     if da.is_valid(): 
         fm = da.cleaned_data['first_name']
         lm = da.cleaned_data['last_name']
         em = da.cleaned_data['email']
         co = da.cleaned_data['comment']
         reg = Contact(first_name=fm,last_name=lm,email=em,comment=co)
         reg.save()
         
        #  return redirect("main:home")
# message concept used here...@
         messages.info(request,'Your data saved TO Admin , You Cannot Chainge contact data')
    else:
     da = ContactForm()
    lop = Contact.objects.all()   
    return render(request, 'main/contact.html',{'form':da,'pizaa':lop})




# gallery page

def gallery(request):
   
 if request.method == 'POST':
    form = ImagesForms(request.POST,request.FILES)
    if form.is_valid():
     form.save()
     messages.success(request,'Your Image is Succesfull saved')
 form = ImagesForms()
 img = Image.objects.all()
 return render(request, 'main/gallery.html',{'form':form,'img':img})



def Email_view(request):
    if request.method=='POST':
        to = request.POST.get('email')
        sub = request.POST.get('subject')
        msg = request.POST.get('message')

        email = EmailData(email=to,subject=sub,message=msg)
        email.save()
        email = send_mail(sub,msg,EMAIL_HOST_USER,[to])

        if email:
            return HttpResponse("Your Enquiry Succesfully saved ")
        else:
            return HttpResponse("Not sended Try agina Your email not valid")

    return render(request, 'main/Email_view_show.html')


                                                                                                                      

main/templates/main/Email_view_show.html
{% extends "main/base.html" %}
{% load static %}



{% block content %}

<style>
  

    table {
        text-align: center;
        border: 1px ridge black;

    }

    .box {
        border: 2px dashed black;
        margin-left: 350px;
        margin-right: 400p;
        margin-top: -410px;
    }

    .gifymail {
        width: 200px;
        height: 70px;
        margin: auto 350px;
        background-color: black;
    }
    .sidebarimage{
        
        width: 320px;
        height: 370px;
        padding: auto;
        margin-top: 50px;
        margin-left: 7px;

    }

</style>


<img src="{% static 'images/mail.jpg' %}" alt="" class="sidebarimage" class="img-fluid">


<div class="box">

    <table>
        <form action="{% url 'main:email' %}" method="POST">
            {% csrf_token %}
            <div class="alert alert-info text-primary text-center bg-warning w-8">MAIL SENDING PROCESS</div>


            <div class="form-roup">
                <!-- images mail sent -->
                <img src="https://uk.teamunify.com/hsst/news/358c2882a2b14ac38e9a7dda004731c6/untitled-1_064446.gif"
                    alt="no images" class="gifymail">
            </div>

            <div class="form-group">
                <label for="exampleFormControlInput1">Enter Your Email ID:)</label>
                <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com"
                    name="email">
            </div>

            <div class="form-group">
                <label for="exampleFormControlInput1">Enter Your Subject Title:)</label>
                <input type="text" class="form-control" id="exampleFormControlInput1"
                    placeholder="Nice Application creatae" name="subject">
            </div>


            <div class="form-group">
                <label for="exampleFormControlTextarea1">Write Your Message:)</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" cols="5"
                    placeholder="messages.." name="message"></textarea>
            </div>
  
        <center>
            <input type="submit" value="Submit" class="btn btn-info bg-info py-auto">
            <input type="reset" value="Cancel" class="btn btn-primary bg-warning py-auto">
        </center>
     

        </form>
    </table>
</div>
{% endblock content %}

main/templates/main/addmovies.html
{% extends 'main/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}

<style>
    .form-tap {
        background-color: lightgreen;
        margin-top: 30px;
        width: 490px;
        line-height: 1.0px;
        text-align: center;
        text-overflow: ellipsis;
        font-weight: 800;
    }

    h3 {
        margin-top: -50px;
    }

    #blink {
        width: 400px;
        height: 350px;
        border-radius: 5%;
        margin-top: 50px image-rendering: -moz-crisp-edges;
        animation: blinker 5s linear;

    }

    @keyframes blinker {
        100% {
            opacity: 0;
        }
    }

    .midlepont{
        margin-left: 560px;
        margin-top: -890px;

        height: 660px;
        width: 680px;
}
</style>



<div class="jumbotron">
    <h3 class="text-center text-primary bg-dark "> ANY COLLEGE CREATING </h3>

    <p>any college names uplode your data <small>But give Genioune

        </small>A college management system built using Django framework. It is designed for interactions between
        students and College. Features include rating ,feedback, gallery ,mail notification </p>

    <div class="row">

        <div class="col-sm-4">
            <div class="container form-tap">
                <div class="card">
                    <div class="card-body">
                        <h3 class="text-center text-info">NEW-COLLEGE</h3>
                        <form action="" method="POST">
                            {% csrf_token %}
                            {{ form | crispy }}

                            <input type="submit" value="{{ controller }}" class="btn btn-danger">
                        </form>
                    </div>
                </div>
            </div>
        </div>



    </div>


</div>

<img src="https://i.pinimg.com/600x315/34/d5/f9/34d5f902c7d035dd5da1cbfe3acc984e.jpg" alt="" class="midlepont">


<div class="jumbotron">

    <h3>NELLURE COLLEGE IMAGES </h3>

    <div class="row mt-2">
        <div class="col-sm-4 col-sm-4">
            <img class="img-fluid" src="{% static 'images/vsu1.jpg' %}" id="blink" alt="...">
        </div>

        <div class="col-sm-4 col-sm-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college10.jpg' %}" id="blink" alt="...">
        </div>
        <div class="col-sm-4 col-sm-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college11.jpg' %}" id="blink" alt="...">
        </div>

    </div>

    <div class="row mt-2">

        <div class="col-sm-4 col-md-4 ">
            <img class="img-fluid" src="{% static 'images/newcolleges/college1.jpg' %}" id="blink" alt="...">
        </div>
        <div class="col-sm-4 col-md-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college2.jpg' %}" id="blink" alt="...">
        </div>
        <div class="col-sm-4 col-md-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college3.jpg' %}" id="blink" alt="...">
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-sm-4 col-md-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college4.jpg' %}" id="blink" alt="...">
        </div>
        <div class="col-sm-4 col-md-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college5.jpg' %}" id="blink" alt="...">
        </div>
        <div class="col-sm-4 col-md-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college16.jpg' %}" id="blink" alt="...">
        </div>

    </div>
    <div class="row mt-2">
        <div class="col-sm-4 col-md-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college6.jpg' %}" id="blink" alt="...">
        </div>
        <div class="col-sm-4 col-md-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college7.jpg' %}" id="blink" alt="...">
        </div>
        <div class="col-sm-4 col-md-4">
            <img class="img-fluid" src="{% static 'images/logos.jpg' %}" id="blink" alt="...">
        </div>
    </div>

    <div class="row mt-2">
        <div class="col-sm-4 col-sm-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college1.jpg' %}" id="blink" alt="...">
        </div>

        <div class="col-sm-4 col-sm-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college13.jpg' %}" id="blink" alt="...">
        </div>
        <div class="col-sm-4 col-sm-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college8.jpg' %}" id="blink" alt="...">
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-sm-4 col-sm-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college15.jpg' %}" id="blink" alt="...">
        </div>

        <div class="col-sm-4 col-sm-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college17.jpg' %}" id="blink" alt="...">
        </div>
        <div class="col-sm-4 col-sm-4">
            <img class="img-fluid" src="{% static 'images/newcolleges/college18.jpg' %}" id="blink" alt="...">
        </div>
    </div>
</div>
</div>
</div>




{% endblock %}

main/templates/main/base.html
{% load static %}
<!doctype html>

<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- # logo vsu icon  -->
  <link rel="icon" href="{% static 'images/logos.jpg' %}">


  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">


  <title>::)VSU_COLLEGE::)</title>

</head>
<style>
  .nav-link {
    color: rosybrown;
    /* background-color:rgb(133, 125, 125); */
    font-size: 18px;
    text-shadow: 1.5px 0.5px darkblue;
    border-radius: 5%;
    border: 1px ridge cyan;
    overflow: hidden;
    text-align:center;


  }
  .nav-link::hover{
    color: brown;
  }

</style>


<body>







  <div class="col-sm-12">

    <nav class="navbar navbar-expand-sm navbar-warning bg-white text-white">
      <img src="{% static 'images/logos.jpg' %}" height="40px" />
      <!-- <img  src="{% static 'images/vsu1.jpg' %}" alt="no logo images" class="img-fluid" width="98%" height="98%"> -->
      <a class="navbar-brand " href="{% url 'main:home' %}">VSU</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" style="color:rgb(25, 10, 233)" href="{% url 'main:main' %}">HOME<span
                class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" style="color:rgb(121, 220, 233)" href="{% url 'main:home' %}">RATINg</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" style="color:rgb(255, 0, 191)" href="{% url 'main:abt' %}">ABOUT</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" style="color:rgb(0, 82, 102)" href="{% url 'main:email' %}">MAILSENDING</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="color:rgb(255, 0, 149)" href="{% url 'main:gallery' %}">GALLERY</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" style="color:rgb(20, 29, 29)" href="{% url 'main:add_movies' %}">NEWCOLLEGE</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" style="color:rgba(103, 153, 88, 0.877)" href="{% url 'main:contact' %}">CONTACT</a>
          </li>



          {% if user.is_authenticated %}

          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <small style="color:rgb(122, 114, 114; background-color: white;)">{{ user.username }}</small>
            </a>
            <div class="dropdown-menu " aria-labelledby="navbarDropdown">
              <a class="dropdown-item active" style="color:rgb(223, 231, 148)" href="#">My Profile</a>
               <!-- admin site implement -->

              <div class="dropdown-divider"></div>
              <a class="dropdown-item active" style="color:rgb(200, 194, 226)" href="{% url 'admin:index' %}">ADMIN-SITE</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item active" style="color:rgb(45, 175, 95)" href="{% url 'accounts:logout' %}">Logout</a>
            </div>

           
          
             
            </div>


          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" style="color:rgb(117, 57, 167)" href="{% url 'accounts:login' %}">LOGIN</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" style="color:rgba(91, 112, 58, 0.74)" href="{% url 'accounts:register' %}">REGISTER</a>
          </li>


          {% endif %}

        </ul>
    
        <form class="form-inline my-0 my-sm-0" method="GET" action="{% url 'main:home' %}">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="title"><button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
         
        </form>
       </div>
      
    </nav>

    {% block content %}





    {% endblock %}



    <footer class="text-center text-warning bg-dark ">
      <center>
        <p class="float-end"><a href="#"class="btn btn-primary bg-info">Back to Home</a></p>
           <p>&copy; 2019–2021 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms&Condition</a><br>
      
           <a href="">DAJNGOADI</a>
      <br>
      <a href="http://aditooyou.pythonanywhere.com/home/">www.DJANGOADI.com</a>
      <br>
      <a href="http://adi3you.pythonanywhere.com/login/">www.ADItoyou.com</a>
      
        </center>
         </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"></script>
  </div>
</body>

</html>

main/templates/main/details.html
{% extends 'main/base.html' %}


{% block content %}

<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <img src="{{ movie.image }}" alt="{{ movie.name }}" class="img-fluid">
            </div>
            <div class="col-md-8">
                <h3 class="text-center">
                   <h4 class="text-info">College Name & Group:-{{ movie.name }}</h4>
                </h3>
                <p class="text-primary">Description:-{{ movie.description }}</p>
                <h5 class="text-dark">Director: {{ movie.director }}</h5>
                <h5 class="text-warning">Joining Date: {{ movie.cast }}</h5>
                <h5 class="text-success">Rating: {{ average }}/10</h5>

                {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser %}
                        <a href="{% url 'main:edit_movies' movie.id %}" class="btn btn-warning">EDIT DETAILES</a>
                        <a href="{% url 'main:delete_movie' movie.id %}" class="btn btn-danger"  onclick="return confirm('Are you sure you want to delete this Permnantely?');">Delete THIS</a>
                       
                    {% endif %}
                {% endif %}
                
            </div>
        </div>
    </div>
    </div>

    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">ADD COLLEGE</h3>
            <form action="{% url 'main:add_review' movie.id %}" method="POST">
                {% csrf_token %}
                <label for="comment">REVIEW</label>
                <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>

                <label for="rating">RATING</label>
                <input type="range" id="rangeInput" 
                    name="rating" min="0" max="10" value="0" step="0.5"
                    oninput="amount.value=rangeInput.value">                                                       
         
         <output name="amount" id="amount" for="rangeInput">0</output>
                
                <br>
                <input type="submit" class="btn btn-danger" value="Add Review">
            </form>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">REVIEWS</h3>
            {% for review in reviews %}
                <div class="card" style="background-color: #f5eeee;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                <h5 class="text-left">{{ review.user.username }}</h5>
                                <h5>{{ review.rating }}</h5>
                                {% if request.user == review.user %}
                                <a href="{% url 'main:edit_review' movie.id review.id %}">Edit</a>
                                <a href="{% url 'main:delete_review' movie.id review.id %}" onclick="return confirm('Are you sure you want to delete this?');">Delete</a>
                                {% endif %}

                            </div>
                            <div class="col-md-9">
                                <p>{{ review.comment }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

main/templates/main/editreview.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}


{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Edit Review</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form | crispy }}
                {% if error %}
                    <strong style="color: red;">{{ error }}</strong>
                {% endif %}
                <input type="submit" value="Save Changes" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% load static %}
{% block content %}


<div class="container">
    <br>
    <div class="card" id="backdrop">
        <div class="card-body">
            <div class="row">
                {% for movie in movies %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                            <img src="{{ movie.image }}" alt="" class="img-fluid" width="75%">
                            <h3 class="text-center">{{ movie.name }}</h3>
                            
                            <i class="text-center">{{ movie.release_date }}</i>
                            <a href="{% url 'main:detail' movie.id %}">Read More</a>
                        </div>
                        
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock %}